pipeline {
    agent {
        node {
            label 'AGENT-1'
        
        }
    }
    
    // environment { 
    //    GREETING = 'hello jenkins user add web hook'
    // }

    // options {
    //     // Timeout counter starts AFTER agent is allocated
    //     timeout(time: 1, unit: 'HOURS')
    // }

    parameters {
        

        choice(name: 'action', choices: ['apply', 'destroy'], description: 'Pick something')

        
    }
    
    stages {
        stage('init') {
            steps {
                sh """
                  cd 01-vpc
                  terraform init -reconfigure

                """
            }
        }
        stage('plam') {
            steps {
                sh """
                  cd 01-vpc
                  terraform init -reconfigure

                """

            }
        }
        stage('Deploy') {
            when {
                expression { 
                    params.action == 'apply'
                }
            }
            input {
                message "Should we continue?"
                ok "Yes, we should."
                // submitter "alice,bob"
                // parameters {
                //     string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
                // }
            }
            steps {
                sh """
                    cd 01-vpc
                    terraform apply -auto-approve
                """
            }
        }
        // stage('check params') {
        //     steps {
        //         sh """
                
        //            echo "Hello ${params.PERSON}"

        //            echo "Biography: ${params.BIOGRAPHY}"

        //            echo "Toggle: ${params.TOGGLE}"

        //            echo "Choice: ${params.CHOICE}"

        //            echo "Password: ${params.PASSWORD}"
                
        //         """
                
                
                

        //     }
        // }
           
    }
    post { 
        always { 
            echo 'I will always say Hello again!'
        }
        failure { 
            echo 'when indicate job failure'
        }
        success { 
            echo 'when job success'
        }
    }
}


